name: "Setup Nix with Cache"
description: "Sets up Nix and configures caching"

runs:
  using: "composite"
  steps:
    - uses: nixbuild/nix-quick-install-action@v30
      shell: bash
    - uses: nix-community/cache-nix-action@v6
      shell: bash
      with:
        primary-key:
          nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
        gc-max-store-size-linux: 2G
        purge: true
        purge-prefixes: nix-${{ runner.os }}-
        purge-created: 0
        purge-primary-key: never
